# Basis-Image (Nginx)
FROM nginx:latest

# Website-Inhalt in den Nginx-Webroot kopieren
COPY ./App/Website /usr/share/nginx/html

# Port 80 freigeben (Standard für HTTP)
EXPOSE 80

# Nginx im Vordergrund starten (für Docker-Compatibilität)
CMD ["nginx", "-g", "daemon off;"]